In [1]:
import os
from download_data_functions import *
from common_functions import *
import sqlite3

In [2]:
with open('last_known_quarter.txt') as f:
    last_known_quarter = f.read()

last_known_quarter

'25-1T'

In [3]:
key_list = create_key_list(last_quarter=last_known_quarter)
key_list

['16-2T',
 '16-3T',
 '16-4T',
 '17-1T',
 '17-2T',
 '17-3T',
 '17-4T',
 '18-1T',
 '18-2T',
 '18-3T',
 '18-4T',
 '19-1T',
 '19-2T',
 '19-3T',
 '19-4T',
 '20-1T',
 '20-2T',
 '20-3T',
 '20-4T',
 '21-1T',
 '21-2T',
 '21-3T',
 '21-4T',
 '22-1T',
 '22-2T',
 '22-3T',
 '22-4T',
 '23-1T',
 '23-2T',
 '23-3T',
 '23-4T',
 '24-1T',
 '24-2T',
 '24-3T',
 '24-4T',
 '25-1T']

In [4]:
url_list = create_url_list(key_list)
url_list

['https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2doTrim_2016_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3erTrim_2016_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4toTrim_2016_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1er_Trim_2017_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2017_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2017_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2017_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2018_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2018_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2018_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2018_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2019_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2019_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2019_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2019_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2020_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2020_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2020_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2020_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2021_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2021_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2021_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2021_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2022_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2022_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2022_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2022_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2023_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2023_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2023_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2023_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2024_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2024_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2024_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2024_txt.zip',
 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2025_txt.zip']

In [5]:
url_dict = create_known_urls(last_known_quarter)
url_dict

{'16-2T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2doTrim_2016_txt.zip',
 '16-3T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3erTrim_2016_txt.zip',
 '16-4T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4toTrim_2016_txt.zip',
 '17-1T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1er_Trim_2017_txt.zip',
 '17-2T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2017_txt.zip',
 '17-3T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2017_txt.zip',
 '17-4T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2017_txt.zip',
 '18-1T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2018_txt.zip',
 '18-2T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2018_txt.zip',
 '18-3T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2018_txt.zip',
 '18-4T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2018_txt.zip',
 '19-1T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2019_txt.zip',
 '19-2T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2019_txt.zip',
 '19-3T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2019_txt.zip',
 '19-4T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2019_txt.zip',
 '20-1T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2020_txt.zip',
 '20-2T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2020_txt.zip',
 '20-3T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2020_txt.zip',
 '20-4T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2020_txt.zip',
 '21-1T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2021_txt.zip',
 '21-2T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2021_txt.zip',
 '21-3T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2021_txt.zip',
 '21-4T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2021_txt.zip',
 '22-1T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2022_txt.zip',
 '22-2T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2022_txt.zip',
 '22-3T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2022_txt.zip',
 '22-4T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2022_txt.zip',
 '23-1T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2023_txt.zip',
 '23-2T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2023_txt.zip',
 '23-3T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2023_txt.zip',
 '23-4T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2023_txt.zip',
 '24-1T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2024_txt.zip',
 '24-2T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2024_txt.zip',
 '24-3T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2024_txt.zip',
 '24-4T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2024_txt.zip',
 '25-1T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2025_txt.zip'}

In [6]:
create_folder_and_download(url_dict)

Downloading files: 100%|██████████| 36/36 [00:49<00:00,  1.39s/it]

In [7]:
check_zip_files()

It looks like all the zip files are valid

In [8]:
# Extracting, renaming and moving the data. Also deletes the zip folder
extract_all_and_remove_folder(url_dict)

In [9]:
check_file_existence(url_dict)

All the files for the individual dataset are available.
All the files for the hogar dataset are available.

In [10]:
base_path = 'data/hogar'
hogar_file_list = sorted(os.listdir(base_path))
hogar_file_paths = [os.path.join(base_path, file) for file in hogar_file_list]

hogar = process_txt_files(hogar_file_paths)
hogar

Processing file: data/hogar/16-2T-hogar.txt, shape: (18796, 88)
Processing file: data/hogar/16-3T-hogar.txt, shape: (18800, 88)
Processing file: data/hogar/16-4T-hogar.txt, shape: (18372, 88)
Processing file: data/hogar/17-1T-hogar.txt, shape: (18477, 88)
Processing file: data/hogar/17-2T-hogar.txt, shape: (18871, 88)
Processing file: data/hogar/17-3T-hogar.txt, shape: (18806, 88)
Processing file: data/hogar/17-4T-hogar.txt, shape: (18793, 88)
Processing file: data/hogar/18-1T-hogar.txt, shape: (18624, 88)
Processing file: data/hogar/18-2T-hogar.txt, shape: (18586, 88)
Processing file: data/hogar/18-3T-hogar.txt, shape: (18364, 88)
Processing file: data/hogar/18-4T-hogar.txt, shape: (18616, 88)
Processing file: data/hogar/19-1T-hogar.txt, shape: (19338, 88)
Processing file: data/hogar/19-2T-hogar.txt, shape: (19251, 88)
Processing file: data/hogar/19-3T-hogar.txt, shape: (18610, 88)
Processing file: data/hogar/19-4T-hogar.txt, shape: (19035, 88)
Processing file: data/hogar/20-1T-hogar.txt, shape: (16845, 88)
Processing file: data/hogar/20-2T-hogar.txt, shape: (11976, 88)
Processing file: data/hogar/20-3T-hogar.txt, shape: (13503, 88)
Processing file: data/hogar/20-4T-hogar.txt, shape: (14442, 88)
Processing file: data/hogar/21-1T-hogar.txt, shape: (15423, 88)
Processing file: data/hogar/21-2T-hogar.txt, shape: (15620, 88)
Processing file: data/hogar/21-3T-hogar.txt, shape: (16285, 88)
Processing file: data/hogar/21-4T-hogar.txt, shape: (17037, 88)
Processing file: data/hogar/22-1T-hogar.txt, shape: (16898, 88)
Processing file: data/hogar/22-2T-hogar.txt, shape: (17367, 88)
Processing file: data/hogar/22-3T-hogar.txt, shape: (16886, 88)
Processing file: data/hogar/22-4T-hogar.txt, shape: (16740, 88)
Processing file: data/hogar/23-1T-hogar.txt, shape: (16815, 88)
Processing file: data/hogar/23-2T-hogar.txt, shape: (16990, 88)
Processing file: data/hogar/23-3T-hogar.txt, shape: (16656, 88)
Processing file: data/hogar/23-4T-hogar.txt, shape: (16462, 98)
Processing file: data/hogar/24-1T-hogar.txt, shape: (16104, 98)
Processing file: data/hogar/24-2T-hogar.txt, shape: (16453, 98)
Processing file: data/hogar/24-3T-hogar.txt, shape: (16650, 98)
Processing file: data/hogar/24-4T-hogar.txt, shape: (16511, 98)
Processing file: data/hogar/25-1T-hogar.txt, shape: (15984, 98)

shape: (618_986, 102)
┌────────────────────────────┬──────┬───────────┬───────────┬───┬────────┬────────┬────────┬───────┐
│ CODUSU                     ┆ ANO4 ┆ TRIMESTRE ┆ NRO_HOGAR ┆ … ┆ V21_03 ┆ V22_02 ┆ V22_03 ┆ V2_01 │
│ ---                        ┆ ---  ┆ ---       ┆ ---       ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---   │
│ str                        ┆ i32  ┆ i32       ┆ i32       ┆   ┆ i32    ┆ i32    ┆ i32    ┆ i32   │
╞════════════════════════════╪══════╪═══════════╪═══════════╪═══╪════════╪════════╪════════╪═══════╡
│ TQRMNOQUXHKOKMCDEGKDB00475 ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 140                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNOQQYHMMKTCDEGKDB00475 ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 009                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNORVUHJMKSCDEGKDB00475 ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 326                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNOPQUHMMKTCDEGKDB00475 ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 005                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNORVRHJMKSCDEGKDB00475 ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 324                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ …                          ┆ …    ┆ …         ┆ …         ┆ … ┆ …      ┆ …      ┆ …      ┆ …     │
│ TQRMNOSXVHJMLOCDEGGFB00875 ┆ 2025 ┆ 1         ┆ 1         ┆ … ┆ 2      ┆ 1      ┆ 2      ┆ 2     │
│ 746                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNOQVQHLMLOCDEGGFB00852 ┆ 2025 ┆ 1         ┆ 1         ┆ … ┆ 2      ┆ 2      ┆ 2      ┆ 0     │
│ 621                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNOSVYHKOLMCDEGGFB00860 ┆ 2025 ┆ 1         ┆ 1         ┆ … ┆ 2      ┆ 1      ┆ 2      ┆ 1     │
│ 046                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNOQWQHJNLRCDEGGFB00875 ┆ 2025 ┆ 1         ┆ 1         ┆ … ┆ 2      ┆ 2      ┆ 2      ┆ 1     │
│ 615                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNOQWRHJNLRCDEGGFB00875 ┆ 2025 ┆ 1         ┆ 1         ┆ … ┆ 2      ┆ 2      ┆ 2      ┆ 0     │
│ 576                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
└────────────────────────────┴──────┴───────────┴───────────┴───┴────────┴────────┴────────┴───────┘

In [11]:
from collections import Counter

counts = Counter(hogar.columns)

# Find items that appear more than once
duplicates = [item for item, count in counts.items() if count > 1]
print(duplicates)

[]

In [12]:
old_cols = set(read_and_format('data/hogar/23-3T-hogar.txt').columns)
new_cols = set(read_and_format('data/hogar/23-4T-hogar.txt').columns)
print("Added in 23-4T:", new_cols - old_cols)
print("Removed in 23-4T:", old_cols - new_cols)

Added in 23-4T: {'V5_02', 'V21_02', 'V22_02', 'V2_02', 'V5_03', 'V11_02', 'V2_03', 'V22_01', 'V21_03', 'V11_01', 'V2_01', 'V22_03', 'V5_01', 'V21_01'}
Removed in 23-4T: {'V11', 'V21', 'V22', 'V5'}

In [13]:
hogar_cols = set(hogar.columns)
print("Columns in the final DataFrame that are not in 23-4T:",
      hogar_cols - new_cols)

Columns in the final DataFrame that are not in 23-4T: {'V11', 'V21', 'V22', 'V5'}

In [14]:
save_dataframe_as_zip(hogar, "hogar_data.zip", "hogar_data.csv")

DataFrame saved and compressed as hogar_data.zip

In [15]:
base_path = 'data/individual'
individual_file_list = sorted(os.listdir(base_path))
individual_file_paths = [os.path.join(base_path, file)
                         for file in individual_file_list]

individual = process_txt_files(individual_file_paths)
individual

Processing file: data/individual/16-2T-individual.txt, shape: (59811, 177)
Processing file: data/individual/16-3T-individual.txt, shape: (59550, 177)
Processing file: data/individual/16-4T-individual.txt, shape: (58154, 177)
Processing file: data/individual/17-1T-individual.txt, shape: (58675, 177)
Processing file: data/individual/17-2T-individual.txt, shape: (59755, 177)
Processing file: data/individual/17-3T-individual.txt, shape: (58721, 177)
Processing file: data/individual/17-4T-individual.txt, shape: (58181, 177)
Processing file: data/individual/18-1T-individual.txt, shape: (57951, 177)
Processing file: data/individual/18-2T-individual.txt, shape: (57835, 177)
Processing file: data/individual/18-3T-individual.txt, shape: (56879, 177)
Processing file: data/individual/18-4T-individual.txt, shape: (57418, 177)
Processing file: data/individual/19-1T-individual.txt, shape: (59369, 177)
Processing file: data/individual/19-2T-individual.txt, shape: (59258, 177)
Processing file: data/individual/19-3T-individual.txt, shape: (57229, 177)
Processing file: data/individual/19-4T-individual.txt, shape: (58519, 177)
Processing file: data/individual/20-1T-individual.txt, shape: (51643, 177)
Processing file: data/individual/20-2T-individual.txt, shape: (37132, 177)
Processing file: data/individual/20-3T-individual.txt, shape: (41685, 177)
Processing file: data/individual/20-4T-individual.txt, shape: (43767, 177)
Processing file: data/individual/21-1T-individual.txt, shape: (46693, 177)
Processing file: data/individual/21-2T-individual.txt, shape: (47085, 177)
Processing file: data/individual/21-3T-individual.txt, shape: (48668, 177)
Processing file: data/individual/21-4T-individual.txt, shape: (50154, 177)
Processing file: data/individual/22-1T-individual.txt, shape: (49706, 177)
Processing file: data/individual/22-2T-individual.txt, shape: (50614, 177)
Processing file: data/individual/22-3T-individual.txt, shape: (49232, 177)
Processing file: data/individual/22-4T-individual.txt, shape: (48545, 177)
Processing file: data/individual/23-1T-individual.txt, shape: (48638, 177)
Processing file: data/individual/23-2T-individual.txt, shape: (49072, 177)
Processing file: data/individual/23-3T-individual.txt, shape: (48335, 177)
Processing file: data/individual/23-4T-individual.txt, shape: (47337, 235)
Processing file: data/individual/24-1T-individual.txt, shape: (46050, 235)
Processing file: data/individual/24-2T-individual.txt, shape: (47151, 235)
Processing file: data/individual/24-3T-individual.txt, shape: (47564, 235)
Processing file: data/individual/24-4T-individual.txt, shape: (46860, 235)
Processing file: data/individual/25-1T-individual.txt, shape: (45425, 235)

shape: (1_868_661, 239)
┌───────────────────┬──────┬───────────┬───────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ CODUSU            ┆ ANO4 ┆ TRIMESTRE ┆ NRO_HOGAR ┆ … ┆ P_GDECCF ┆ P_PDECCF ┆ P_IDECCF ┆ P_ADECCF │
│ ---               ┆ ---  ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str               ┆ i32  ┆ i32       ┆ i32       ┆   ┆ i32      ┆ i32      ┆ i32      ┆ i32      │
╞═══════════════════╪══════╪═══════════╪═══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ TQRMNOQTUHMMTQCDE ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ IJAH00483381      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOQTUHMMTQCDE ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ IJAH00483381      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOQTUHMMTQCDE ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ IJAH00483381      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOPSRHLOLRCDE ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ IJAH00483068      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNORUVHLNMNCDE ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ IJAH00484887      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ …                 ┆ …    ┆ …         ┆ …         ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ TQRMNOPWQHLMKUCDE ┆ 2025 ┆ 1         ┆ 1         ┆ … ┆ 8        ┆ null     ┆ 8        ┆ 8        │
│ GJBF00852927      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOPWQHLMKUCDE ┆ 2025 ┆ 1         ┆ 1         ┆ … ┆ 8        ┆ null     ┆ 8        ┆ 8        │
│ GJBF00852927      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOSSVHLMLMCDE ┆ 2025 ┆ 1         ┆ 1         ┆ … ┆ 10       ┆ null     ┆ 10       ┆ 10       │
│ GJBF00852929      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOSSXHLMLMCDE ┆ 2025 ┆ 1         ┆ 2         ┆ … ┆ 10       ┆ null     ┆ 10       ┆ 10       │
│ GJBF00858297      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOSSXHLMLMCDE ┆ 2025 ┆ 1         ┆ 2         ┆ … ┆ 10       ┆ null     ┆ 10       ┆ 10       │
│ GJBF00858297      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
└───────────────────┴──────┴───────────┴───────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [16]:
save_dataframe_as_zip(individual, 'individual_data.zip', 'individual_data.csv')

DataFrame saved and compressed as individual_data.zip

In [17]:
# Remove the data folder from disk
shutil.rmtree('data')