In [1]:
from update_data_functions import *
from common_functions import save_dataframe_as_zip

In [2]:
with open('last_known_quarter.txt') as f:
    last_known_quarter = f.read()

last_known_quarter

'25-1T'

In [3]:
url_dict = create_unknown_urls(4, last_known_quarter)
url_dict

{'25-2T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2025_txt.zip',
 '25-3T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2025_txt.zip',
 '25-4T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2025_txt.zip',
 '26-1T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_1_Trim_2026_txt.zip'}

In [4]:
valid_urls = test_urls(url_dict)
valid_urls

{'25-2T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_2_Trim_2025_txt.zip',
 '25-3T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_3_Trim_2025_txt.zip',
 '25-4T': 'https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_usu_4_Trim_2025_txt.zip'}

In [5]:
release_zip_files = download_release_zips()

In [6]:
(hogar_release, ind_release) = extract_release_zip_to_memory(release_zip_files)
del release_zip_files

In [7]:
new_zip_files = download_new_zips_to_memory(valid_urls)

In [8]:
new_hogar, new_ind = extract_new_zips_to_memory(new_zip_files)
del new_zip_files

In [9]:
hogar = read_text_and_merge(hogar_release, new_hogar)
del hogar_release
del new_hogar

hogar

shape: (666_549, 102)
┌────────────────────────────┬──────┬───────────┬───────────┬───┬────────┬────────┬────────┬───────┐
│ CODUSU                     ┆ ANO4 ┆ TRIMESTRE ┆ NRO_HOGAR ┆ … ┆ V21_03 ┆ V22_02 ┆ V22_03 ┆ V2_01 │
│ ---                        ┆ ---  ┆ ---       ┆ ---       ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---   │
│ str                        ┆ i64  ┆ i64       ┆ i64       ┆   ┆ str    ┆ str    ┆ str    ┆ str   │
╞════════════════════════════╪══════╪═══════════╪═══════════╪═══╪════════╪════════╪════════╪═══════╡
│ TQRMNOQUXHKOKMCDEGKDB00475 ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 140                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNOQQYHMMKTCDEGKDB00475 ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 009                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNORVUHJMKSCDEGKDB00475 ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 326                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNOPQUHMMKTCDEGKDB00475 ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 005                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNORVRHJMKSCDEGKDB00475 ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 324                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ …                          ┆ …    ┆ …         ┆ …         ┆ … ┆ …      ┆ …      ┆ …      ┆ …     │
│ TQRMNOSQUHKOKNCDEHPJB00869 ┆ 2025 ┆ 4         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 447                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNOPWXHMMLNCDEHPJB00890 ┆ 2025 ┆ 4         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 492                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNOPXUHJLKTCDEHPJB00873 ┆ 2025 ┆ 4         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 127                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNOPWSHJMKUCDEHPJB00892 ┆ 2025 ┆ 4         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 689                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
│ TQRMNORXYHLMKPCDEIHJF00892 ┆ 2025 ┆ 4         ┆ 1         ┆ … ┆ null   ┆ null   ┆ null   ┆ null  │
│ 996                        ┆      ┆           ┆           ┆   ┆        ┆        ┆        ┆       │
└────────────────────────────┴──────┴───────────┴───────────┴───┴────────┴────────┴────────┴───────┘

In [10]:
save_dataframe_as_zip(hogar, 'hogar_data.zip', 'hogar_data.csv')
del hogar

DataFrame saved and compressed as hogar_data.zip

In [11]:
individual = read_text_and_merge(ind_release, new_ind)
del ind_release
del new_ind

individual

shape: (2_003_396, 239)
┌───────────────────┬──────┬───────────┬───────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ CODUSU            ┆ ANO4 ┆ TRIMESTRE ┆ NRO_HOGAR ┆ … ┆ P_GDECCF ┆ P_PDECCF ┆ P_IDECCF ┆ P_ADECCF │
│ ---               ┆ ---  ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str               ┆ i64  ┆ i64       ┆ i64       ┆   ┆ str      ┆ str      ┆ str      ┆ str      │
╞═══════════════════╪══════╪═══════════╪═══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ TQRMNOQTUHMMTQCDE ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ IJAH00483381      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOQTUHMMTQCDE ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ IJAH00483381      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOQTUHMMTQCDE ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ IJAH00483381      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOPSRHLOLRCDE ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ IJAH00483068      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNORUVHLNMNCDE ┆ 2016 ┆ 2         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ IJAH00484887      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ …                 ┆ …    ┆ …         ┆ …         ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ TQRMNOPXYHKOLLCDE ┆ 2025 ┆ 4         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ HPJB00867227      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOPXYHKOLLCDE ┆ 2025 ┆ 4         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ HPJB00867227      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOPXYHKOLLCDE ┆ 2025 ┆ 4         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ HPJB00867227      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOWPTHKOMLCDE ┆ 2025 ┆ 4         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ HPJB00874368      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
│ TQRMNOWPTHKOMLCDE ┆ 2025 ┆ 4         ┆ 1         ┆ … ┆ null     ┆ null     ┆ null     ┆ null     │
│ HPJB00874368      ┆      ┆           ┆           ┆   ┆          ┆          ┆          ┆          │
└───────────────────┴──────┴───────────┴───────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [12]:
save_dataframe_as_zip(individual, 'individual_data.zip', 'individual_data.csv')
del individual

DataFrame saved and compressed as individual_data.zip

In [13]:
# Save the the new last known quarter
valid_keys = []
for key, url in valid_urls.items():
    valid_keys.append(key)
with open('last_known_quarter.txt', 'w') as f:
    f.write(valid_keys[-1])
    f.close()